{% set name = "insarhub" %}
{% set version = "0.4.0rc1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/i/insarhub/insarhub-{{ version }}.tar.gz
  sha256: 62838db24ff35204b9efe21c5cd1037a0872df80d80c17cfece61fcaea69eb7b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python
  entry_points:
    - insarhub = insarhub.cli.main:main
    - insarhub-app = insarhub.app.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
  run:
    - python >={{ python_min }}
    - gdal >=3.8
    - mintpy
    - asf_search
    - burst2safe
    - cdsapi
    - colorama
    - contextily
    - dask
    - dem_stitcher
    - h5py
    - hyp3_sdk
    - networkx
    - openpyxl
    - psutil
    - pyaps3
    - python-multipart
    - fastapi
    - pysolid
    - pygrib
    - setuptools <81
    - uvicorn
    - rasterio >=1.4
    - sentineleof
    - numpy <2.0
    - imagecodecs <=2026.1.1


test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - insarhub
  commands:
    - pip check
    - insarhub --version
    - insarhub-app --version
about:
  home: https://github.com/jldz9/InSARHub
  license: MIT
  license_file: LICENSE
  summary: "A modular Python framework for automated InSAR and time-series processing."
  doc_url: https://jldz9.github.io/InSARHub/


extra:
  recipe-maintainers:
    - jldz9
